### PR TITLE
Fixes for RFC 2231

### PR DESCRIPTION
**Pull request by sigmavirus24**

### CODE REVIEW

**Comment by tenderlove** [comment]
Can you rebase this please?  Thank you!

**Comment by sigmavirus24** [comment]
On it

**Comment by sigmavirus24** [comment]
Done

**Comment by sigmavirus24** [comment]
:sparkles: :cake: :sparkles:

**Comment by tenderlove** [comment]
Thanks.  Would you mind running the tests? This PR is generating warnings with the new regexps:

```
/Users/aaron/git/rack/lib/rack/multipart.rb:31: warning: nested repeat operator + and ? was replaced with '*'
/Users/aaron/git/rack/lib/rack/multipart.rb:32: warning: nested repeat operator + and ? was replaced with '*'
/Users/aaron/git/rack/lib/rack/multipart.rb:32: warning: nested repeat operator + and ? was replaced with '*'
/Users/aaron/git/rack/lib/rack/multipart.rb:33: warning: nested repeat operator + and ? was replaced with '*'
/Users/aaron/git/rack/lib/rack/multipart.rb:33: warning: nested repeat operator + and ? was replaced with '*'
/Users/aaron/git/rack/lib/rack/multipart.rb:34: warning: nested repeat operator + and ? was replaced with '*'
/Users/aaron/git/rack/lib/rack/multipart.rb:34: warning: nested repeat operator + and ? was replaced with '*'
/Users/aaron/git/rack/lib/rack/multipart.rb:34: warning: nested repeat operator + and ? was replaced with '*'
/Users/aaron/git/rack/lib/rack/multipart.rb:34: warning: nested repeat operator + and ? was replaced with '*'
/Users/aaron/git/rack/lib/rack/multipart.rb:35: warning: nested repeat operator + and ? was replaced with '*'
/Users/aaron/git/rack/lib/rack/multipart.rb:35: warning: nested repeat operator + and ? was replaced with '*'
```

**Comment by sigmavirus24** [comment]
That's interesting, I don't remember seeing those before. I'll take a look at them tonight. Sorry about that

**Comment by tenderlove** [comment]
No problem!  It might just be against trunk Ruby (Ruby 2.3)

**Comment by sigmavirus24** [comment]
On Sat, Jun 13, 2015 at 03:36:31PM -0700, Aaron Patterson wrote:
> No problem!  It might just be against trunk Ruby (Ruby 2.3)

Nah, it shows up in Travis-CI for 2.2 too. I don't think I had 2.2 installed 
last year when I worked on this.

**Comment by sigmavirus24** [comment]
So I took a look at this tonight finally. The interesting thing is that on L31 of `lib/rack/multipart.rb` if I change

```rb
EXTENDED_INITIAL_VALUE = /(?:[a-zA-Z0-9\-]+)?'(?:[a-zA-Z0-9\-]+)?'(?:#{EXTENDED_OTHER_VALUE}+)/
```

to

```rb
EXTENDED_INITIAL_VALUE = /(?:#{EXTENDED_OTHER_VALUE}+)/
```

Those warnings disappear. I'm toying around in [rubular](http://rubular.com/r/P3UuooR4GR) to see if I can find an equivalent regular expression to make Ruby 2.2 happy.

**Comment by sigmavirus24** [comment]
So, the warnings go away (but the tests fail) if we do:

```rb
EXTENDED_INITIAL_VALUE = /([a-zA-Z0-9\-]+)?'([a-zA-Z0-9\-]+)?'(#{EXTENDED_OTHER_VALUE}+)/
```

But in reality, we don't need to capture those matches individually.

**Comment by sigmavirus24** [comment]
@tenderlove here's the fix: https://github.com/rack/rack/pull/892

**Pull request merged**
