### PR TITLE
Remove autoloads for constants no longer shipped with rack

### PR DESCRIPTION
**Pull request by jeremyevans**
Removes the following autoloads:

* File
* Handler
* Server
* Auth::Digest

Sort the remaining autoloads alphabetically.

Fixes #2112

### CODE REVIEW

**Review by ioquatix — APPROVED** [review]

**Comment by p8** [comment]
Should the autoload of Handler be added to rackup? Or should that be removed from rackup altogether?

**Comment by jeremyevans** [comment]
I think it is a good idea to remove `lib/rack/{handler,server}.rb` from rackup.

**Comment by ioquatix** [comment]
They are compatibility shims but basically I agree with you.

**Comment by p8** [comment]
I've created a PR for rackup: https://github.com/rack/rackup/pull/10

**Pull request merged**
