### PR TITLE
Backport support for SameSite=None cookie flag to 2-0-stable branch

### PR DESCRIPTION
**Pull request by misdoro**
Backport https://github.com/rack/rack/pull/1358 to 2-0-stable branch

Chrome is planning to block cookies with SameSite=None not set as early as in February 2020:
https://www.chromium.org/updates/same-site

Current master and potentially 2.1 release are not yet compatible with too many things:
- sidekiq web interface is broken when loaded as sub-route
- grape gem is broken

### CODE REVIEW

**Comment by ioquatix** [comment]
Grape is now fixed, and it was almost entirely due to incorrect usage of Rack.

https://github.com/ruby-grape/grape/pull/1956

**Comment by misdoro** [comment]
@ioquatix @tenderlove will it be possible to include this backport in an oncoming 2.0 release ?

**Comment by rafaelfranca** [comment]
We don't backport new features to stable branches, but I think this is an exception given the change on behavior for Chrome. I'll merge this.

**Comment by cade** [comment]
@rafaelfranca Thanks for backporting this patch! We've got a Rails 5.2 app that we're working on upgrading to 6, but won't be ready in time for the Chrome cookie changes. Any idea when you might release a 2.0.9 version? We'll point to the `2-0-stable` branch for now to pull the changes. Thanks again!

**Comment by tomoyukikashiro** [comment]
@misdoro @rafaelfranca Thank you for your kindful support 👍 👍 
@rafaelfranca Do you have any plan to release `2-0-stable` which includes this PR. ????

**Comment by misdoro** [comment]
:tada: 2.0.9 was released this week-end https://rubygems.org/gems/rack/versions/2.0.9
Thank you @tenderlove!

**Pull request merged**
