### PR TITLE
Make `env['rack.input']` optional.

### PR DESCRIPTION
**Pull request by ioquatix**
Fixes https://github.com/rack/rack/issues/1994. Fixes https://github.com/rack/rack/issues/1995.

### CODE REVIEW

**Comment by ioquatix** [comment]
Ignore the failures in 2.5, it's done this before and seems an issue with rubygems/bundler/ruby-setup AFAICT.

**Review by jeremyevans — CHANGES_REQUESTED** [review]
This will be OK once the the Ruby 2.4/2.5 CI removal is no longer included.  I fixed the CI tests for Ruby 2.5 in #2021.

**Comment by jeremyevans** [comment]
@ioquatix  Can you remove the first commit and then rebase on master?  Then this should be good to merge.

**Comment by ioquatix** [comment]
Okay done.

**Review by jeremyevans — APPROVED** [review]

**Pull request merged**
