### PR TITLE
 Remove `@has_app` from `Rack::Cascade`.

### PR DESCRIPTION
**Pull request by lanzhiheng**
I don't think we need `@has_app` in this class. 

1. `@apps` is an array we can use the `Array#include?` to check if target element in it.
2. if the `@apps` array not very large it is not a good choice to use `Hash` to store the status.

### CODE REVIEW

**Comment by kares** [comment]
... or just use a Set so there's no need to worry about O(n)

**Comment by ioquatix** [comment]
A set is just a wrapper around `Hash`.

**Comment by ioquatix** [comment]
This PR simplifies the implementation but also introduces a performance regression.

I don't know the real world implications of the performance regression - does anyone expect to call `#include?`?

If you can show that this code is not used (frequently), then I prefer the simpler code.

That being said, I have to ask @lanzhiheng to do the work here.

@Jeremy can you comment on your use case?

**Comment by jeremy** [comment]
No idea. 2009 😂

**Comment by ioquatix** [comment]
Thanks for your attention :)

**Pull request merged**
