### PR TITLE
Fix to handle same_site option for session pool

### PR DESCRIPTION
**Pull request by kamipo**
Follow up of #1543.

### CODE REVIEW

**Comment by ioquatix** [comment]
This seems reasonable to me. @jeremyevans WDYT?

**Comment by kamipo** [comment]
I've found this issue at https://buildkite.com/rails/rails/builds/66924#e59fd8a6-3524-46b4-98ae-25369c786941, using subclasses of `Rack::Session::Abstract::Persisted` except `Rack::Session::Cookie` will raise "instance variable @same_site not initialized" warnings.

**Comment by ioquatix** [comment]
Can you confirm this is just to fix warnings, right?

**Comment by ioquatix** [comment]
Sorry, I misunderstood the PR. I've merged it. I will release as part of v2.2.2 tomorrow after I wake up. So, if there are any other issues, please commit it in the next 12 hours and assign it milestone v2.2.2

**Pull request merged**
