### PR TITLE
adding HTTP status codes

### PR DESCRIPTION
**Pull request by tilo**
adding some missing HTTP status codes

### CODE REVIEW

**Comment by perlun** [comment]
Looks sane enough to me. Could we get someone to merge this?

**Comment by gioele** [comment]
With the exception of 418, all these status codes are not defined in any RFC and some of them (for example 420) are used by various frameworks with diverging meanings.

**Comment by talent-io** [comment]
Sorry to jump in this 2 years and a half later. 

I was actually looking for 418 error code, and it seems it's actually been removed by https://github.com/rack/rack/pull/933. So I guess this PR can now be closed :).

**Comment by rafaelfranca** [comment]
@gioele is right. We can't add to rack if they are not in the RFCs. Thank you.

**Pull request closed without merging**
