### PR TITLE
Don't bother pattern matching existing set-cookie for deletion.

### PR DESCRIPTION
**Pull request by ioquatix**
Fixes https://github.com/rack/rack/issues/1840

### CODE REVIEW

**Comment by ioquatix** [comment]
I'm honestly not sure what these tests were trying to achieve. Our deletion logic doesn't matter at all if browsers don't implement it correctly. Because I imagine 99% of people trying to delete cookies would be doing so after the fact it was set in a prior request, so the tests really don't reflect reality.

**Comment by leahneukirchen** [comment]
Please don't commit .DS_Store files..

One use case could be to have middle-ware that removes cookies from some other layer, but I'm not sure how useful that is.

**Comment by ioquatix** [comment]
Oh lol, I don't even know how that happened, I was committing from Linux, but I think I copied the entire repo from my old development laptop haha. Thanks for pointing it out!

**Review by tenderlove — APPROVED** [review]

**Comment by tenderlove** [comment]
If you're sending sensitive information, and then relying on this to delete it, I think your app has bigger problems.  Specifically adding sensitive info, then trying to remove it later seems like a "your app problem" not a "rack should deal with this" problem.  Additionally, the regex match used for detecting if it's the right cookie could be problematic.  Since the app developer has access to the array and can mutate it themselves, why is it our responsibility to try and parse their strings?

(My main gripe with this method are the regular expressions.  If we kept the cookies in a more structured format like objects, I think removing existing ones would be fine)

**Comment by jeremyevans** [comment]
I agree the method implementation is ugly. However, the only reason for `delete_set_cookie_header!` is to do this removal.  If we don't want to do this removal, it would be better to deprecate the method, and just tell people to switch to `delete_set_cookie_header`.  Most internal callers of `delete_set_cookie_header!` are already deprecated, and `delete_cookie_header!` could switch to calling `delete_set_cookie_header`.

**Comment by ioquatix** [comment]
I'm happy to revert this PR and just deprecate the entire method if we all agree to that, I'll do it today.

**Pull request merged**
