### PR TITLE
last slash check optimization

### PR DESCRIPTION
**Pull request by railsme**
`String#end_with?` takes less cpu time and allocates less memory than regular expression

### CODE REVIEW

**Comment by arthurnn** [comment]
hi @railsme , can you provide some benchmarks showing before and after?
Thanks

**Comment by railsme** [comment]
Hi @arthurnn . Here are some benchmarks and short allocation profile results.
```ruby
require 'benchmark/ips'
require 'memory_profiler'

true_path = '/my_mega_true_path/'
false_path = '/my_mega_false_path'

GC.disable

Benchmark.ips do |bm|
  bm.report 'regexp match true' do
    true_path =~ /\/$/
  end
  bm.report 'regexp match false' do
    false_path =~ /\/$/
  end

  bm.report '#end_with? true' do
    true_path.end_with?('/'.freeze)
  end
  bm.report '#end_with? false' do
    false_path.end_with?('/'.freeze)
  end
end

=begin
Results:
Warming up --------------------------------------
   regexp match true   105.475k i/100ms
  regexp match false    93.314k i/100ms
     #end_with? true   165.048k i/100ms
    #end_with? false   150.808k i/100ms
Calculating -------------------------------------
   regexp match true      1.980M (±18.8%) i/s -      9.387M
  regexp match false      1.821M (± 9.6%) i/s -      9.051M
     #end_with? true      7.784M (± 5.6%) i/s -     38.786M
    #end_with? false      7.714M (± 5.1%) i/s -     38.607M
=end

# MemoryProfiler.report do
#   true_path =~ /\/$/
# end.pretty_print
#
# Total allocated: 489 bytes (3 objects)
# Total retained:  320 bytes (2 objects)

# MemoryProfiler.report do
#   false_path =~ /\/$/
# end.pretty_print
#
# Total allocated: 169 bytes (1 objects)
# Total retained:  0 bytes (0 objects)

# MemoryProfiler.report do
#   true_path.end_with?('/'.freeze)
# end.pretty_print
#
# Total allocated: 0 bytes (0 objects)
# Total retained:  0 bytes (0 objects)

# MemoryProfiler.report do
#   false_path.end_with?('/'.freeze)
# end.pretty_print
#
# Total allocated: 0 bytes (0 objects)
# Total retained:  0 bytes (0 objects)
```

**Comment by raggi** [comment]
we use `str[-1] == ?/` elsewhere in the code base.

**Comment by railsme** [comment]
I changed in other places where found this code
```
Warming up --------------------------------------
   regexp match true   123.876k i/100ms
  regexp match false   110.406k i/100ms
   compare last true   173.363k i/100ms
  compare last false   184.667k i/100ms
     #end_with? true   234.371k i/100ms
    #end_with? false   220.078k i/100ms
Calculating -------------------------------------
   regexp match true      1.816M (±19.9%) i/s -      8.671M in   5.055489s
  regexp match false      1.686M (± 6.5%) i/s -      8.501M in   5.063548s
   compare last true      3.067M (±30.0%) i/s -     13.696M in   5.026835s
  compare last false      3.632M (±34.0%) i/s -     14.404M in   5.016203s
     #end_with? true      7.184M (± 7.1%) i/s -     35.859M in   5.016803s
    #end_with? false      6.843M (± 7.6%) i/s -     34.112M in   5.012879s
```

**Pull request merged**
