### PR TITLE
Fixed issue with sending extra POST and GET command from TEMPLATE

### PR DESCRIPTION
**Pull request by rrott**
changed TEMPLATE that tried to not to  GET/POST incorrect url once again just to show "Request information". More information: https://github.com/rack/rack/issues/991

### CODE REVIEW

**Comment by matthewd** [comment]
`req.env` contains something very different from `req.GET` or `req.POST`.

**Comment by rrott** [comment]
My bad, I am sorry.

Now I see that GET and POST update and return RACK_REQUEST_QUERY_HASH and RACK_REQUEST_FORM_HASH respectively. But they have never been shown because of  parse_query that always failed on updating these values.
https://github.com/rack/rack/blob/master/lib/rack/request.rb#L336

I've fixed this to show appropriate data. Could you please have a look?

**Comment by rrott** [comment]
Could you please review it once again?

**Comment by rrott** [comment]
Can you please have a look? 

Note, Travis CI fails on "bundle install" stage, probably because of "This job ran on our new platform for Precise builds. Please read our blog post for more information."

**Comment by jkowens** [comment]
Rack apps should rescue `ParameterTypeError` and `InvalidParameterError` when parsing query parameters and then return a 400 status, which would avoid the issue described.

**Comment by rrott** [comment]
@jkowens Then what do you have [this huge template ](https://github.com/rrott/rack/blob/master/lib/rack/show_exceptions.rb#L110) for?
Should not it be deleted then?

As I see this template as a part of rack and it causes the issue described [here](https://github.com/rack/rack/issues/991)

**Comment by jkowens** [comment]
That template is very useful for displaying traces for any exception other than `ParameterTypeError` and `InvalidParameterError`. Those are the two exceptions Rack expects to be handled, returning a http 400 status (instead of bubbling up to the Rack error handler or being displayed in the browser).

**Pull request closed without merging**
