### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by ioquatix**
Has anyone tried codeql for vulnerability scanning?

### CODE REVIEW

**Comment by jeremyevans** [comment]
I'm not familiar with codeql.  Unless other committers are familiar with it and found it to be helpful (finds real issues, no/few false positives), I'm negative on merging this.

**Comment by ioquatix** [comment]
I actually don't know what it does but it seems interesting. @tenderlove do you know anything about it?

**Comment by tenderlove** [comment]
@ioquatix maybe you should try it on a personal project first?  I'm not super familiar with the tool and I don't want to research it (I've seen it on some repos, but I can't say that it's done anything for me)

**Comment by jeremyevans** [comment]
Funnily enough, I just had a ruby commit fail the CodeQL action due to problems with codeql: https://github.com/ruby/ruby/runs/5861396950

**Comment by ioquatix** [comment]
What does that analysis actually tell you?

**Comment by jeremyevans** [comment]
In that case, the analysis didn't run.  I don't actually know where to look for the results when it does run.

**Comment by ioquatix** [comment]
Maybe this?

https://github.com/ruby/ruby/security/code-scanning

**Comment by ioquatix** [comment]
This actually looks pretty useful?

https://github.com/ruby/ruby/security/code-scanning?query=branch%3Amaster+is%3Aclosed shows all the actionable items.

**Comment by jeremyevans** [comment]
I checked the first 5 closed issues, and all were won't fix/false positive.  Maybe codeql does find real issues, but based on the sample selected, I don't think that looking at the remaining 46 issues is a good use of my time.

**Comment by ioquatix** [comment]
@tenderlove has been investigating regex issues and that's exactly what those look like: https://github.com/ruby/ruby/security/code-scanning/54

**Pull request closed without merging**
