### PR TITLE
Add 'custom exception on params too deep error' change to CHANGELOG.

### PR DESCRIPTION
**Pull request by simi**
- format latest versions changes in consistent way

:information_source: I'll back(forward?)port this to `main` branch as well once merged.

### CODE REVIEW

**Comment by simi** [comment]
:information_source: CI is fixed at https://github.com/rack/rack/pull/1913

**Comment by ioquatix** [comment]
@simi thanks for this do you mind rebasing?

**Comment by simi** [comment]
@ioquatix done

**Comment by ioquatix** [comment]
Thanks!

**Pull request merged**
