### PR TITLE
Multipart part limit backport

### PR DESCRIPTION
**Pull request by byroot**
Fixes: https://github.com/rack/rack/issues/779

I disabled the feature by default so it won't create bad surprises for people that upgrade.

@tenderlove @spastorino for review please.

cc @boourns @orenmazor

### CODE REVIEW

**Comment by tenderlove** [comment]
I'm fine with this.  @spastorino wdyt?

**Comment by spastorino** [comment]
I don't think we should backport features in Rack. Given the careful way releases are made Rack users should just be able to easily upgrade from 1.4 to 1.5 or even to 1.6.

This is a Rails issue and I think we should relax Rack dependency on Rails side.

I know that given the things Rails does with Request, Session, etc that may not be trivial but I still think that trying that is maybe a better idea.

@tenderlove I will leave the decision up to you bro :) :heart: :heart: :heart:

**Comment by tenderlove** [comment]
@spastorino if we can easily relax the dependency on the Rails side, it seems better if we do it there (IMO).

**Comment by byroot** [comment]
I also think relaxing the dependencies on the Rails side is a better idea.

**Comment by spastorino** [comment]
Done in master https://github.com/rails/rails/commit/da175a2b46c4db59cd8c4bd0b9c6c613651e3db0 and 4-2-stable https://github.com/rails/rails/commit/d5e329e8ce1e725405f096a44fc4a14e25c1c785

This won't have any impact anyway because it won't be a 1.7 and we shouldn't do this kind of aggressive change in 4-1-stable. So your issue is not fixed by any of this stuff :(.

I guess your alternatives now are 

1. upgrade to 4.2
2. monkey patch Rack's/Rails' stuff to provide what you want

Ping me if I can help you in any way ...

**Comment by byroot** [comment]
We're already working on upgrading to 4.2 but it will take a while.

But I totally understand the issue, we'll keep our fork for a little while. Thanks again!

**Comment by byroot** [comment]
cc @arthurnn

**Pull request closed without merging**
