### PR TITLE
Backport "Fix some unused variable verbose warnings"

### PR DESCRIPTION
**Pull request by skipkayhil**
Fixes `/usr/local/bundle/gems/rack-3.0.7/lib/rack/sendfile.rb:114: warning: assigned but unused variable - status`

### CODE REVIEW

**Review by jeremyevans — APPROVED** [review]
@headius You may want to look at the JRuby failures here, could be related to the jzlib changes in JRuby 9.4.3.0.

**Review by ioquatix — APPROVED** [review]

**Comment by ioquatix** [comment]
@skipkayhil do you want me to cut a patch release from this?

**Comment by skipkayhil** [comment]
> do you want me to cut a patch release from this?

That would be awesome! Since Rails is testing against Rack 3 by default now that would help a lot with the warning noise

**Comment by ioquatix** [comment]
Okay released, if you can also make a PR updating the change log that would be awesome.

**Comment by skipkayhil** [comment]
> Okay released, if you can also make a PR updating the change log that would be awesome.

I opened one for both `main` and `3-0-stable`. Thanks again for the release!

**Pull request merged**
