### PR TITLE
Omit unnecessary ?s in EXTENDED_INITIAL_VALUE

### PR DESCRIPTION
**Pull request by sigmavirus24**
The ? outside the groups is redundant and Ruby's regular expression engine
rightfully produces a warning when compiling the regular expression.

Removing the ?s prevents the warning from being printed to stderr.

See also: http://rubular.com/r/J4CWeIHQTK

---

This is a quick fix up of the warnings produced by #726

### CODE REVIEW

**Comment by matthewd** [comment]
There seem to be several things amiss here

**Comment by sigmavirus24** [comment]
@matthewd can you elaborate?

**Comment by matthewd** [comment]
* the `?` is not unnecessary
* `EXTENDED_OTHER_PARAMETER` will only match single-byte values
* `DISPPARM` is clearly wrong
* there are no tests that demonstrate any of the above problems
* the removal of the anchors on `RFC2183` is extremely suspicious
* your rubular example is not doing what you think it is

**Comment by jeremy** [comment]
#913

**Pull request closed without merging**
