### PR TITLE
Invalid cookie keys will now raise an error.

### PR DESCRIPTION
**Pull request by ioquatix**
Follow up to <https://github.com/rack/rack/pull/2191> for Rack 3.2+.

### CODE REVIEW

**Review by jeremyevans — CHANGES_REQUESTED** [review]
The unrelated changes to the CHANGELOG and version file makes it look like something went wrong in a rebase.

**Comment by ioquatix** [comment]
Yeah not sure what happened here, the PR is completely bananas. I'll fix it.

**Review by jeremyevans — APPROVED** [review]

**Comment by dentarg** [comment]
@tenderlove Looks like you released this change with rack 3.1.1 (https://my.diffend.io/gems/rack/3.1.0/3.1.1)

**Comment by tenderlove** [comment]
argh, sorry about that. I shipped the wrong branch.  I'll fix it.

**Comment by tenderlove** [comment]
@dentarg v3.1.2 should be shipped now

**Pull request merged**
