### PR TITLE
Add rails smoke tests to external tests.

### PR DESCRIPTION
**Pull request by ioquatix**
We've had a couple of challenges relating to what essentially amount to compatibility issues between Rails and Rack, e.g. <https://github.com/rails/rails/issues/52066>. Let's ensure that Rails' smoke tests all pass as part of Rack's CI. This should give earlier indications about potential issues.

### CODE REVIEW

**Review by jeremyevans — APPROVED** [review]
May want to consider adding Sinatra as an external test as well. Sinatra and Rails probably cover 90% of Rack usage.  But that can be done later.

**Comment by dentarg** [comment]
I'm testing rack-head in the Sinatra repo. Currently there is one known failure: https://github.com/sinatra/sinatra/issues/2014

**Comment by ioquatix** [comment]
@dentarg are you able to create a PR to add Sinatra to the external tests?

**Comment by dentarg** [comment]
I have too little time right now

**Comment by simi** [comment]
> I have too little time right now

I have some. https://github.com/rack/rack/pull/2210

**Pull request merged**
