### PR TITLE
fix: describe module autoloading in config.ru

### PR DESCRIPTION
**Pull request by yumetodo**
It seems to me that described at #1975 is not well documented.

### CODE REVIEW

**Review by jeremyevans — CHANGES_REQUESTED** [review]
Note that the same behavior was true in Rack 2 (need to `require 'rack'` to get autoloading), it just wasn't necessarily safe in Rack 2 to require specific components, since the components didn't specify their dependencies (nor were there tests for requiring specific components).  I think that the difference is that the extracted `rackup` gem only loads the parts of rack that it needs, while in Rack 2, `rackup` does `require 'rack'`.

If you are using a separate server (puma/unicorn/falcon/etc.), I don't think there is a difference in behavior. As that is the vast majority of production usage, this documentation should be specific that it only applies to `rackup`, and moved to the section that discusses `rackup`.

**Comment by yumetodo** [comment]
@jeremyevans Thank you for your review. To follow your review, I move module autoloading section into `rackup` section.

**Review by jeremyevans — APPROVED** [review]
Looks good, thanks!

**Comment by ioquatix** [comment]
This is really great, thanks for pointing out the issue here and making a PR to improve the documentation.

**Pull request merged**
