### PR TITLE
Fix typo `interactively`

### PR DESCRIPTION
**Pull request by TonyCTHsu**
Found a typo while reading through doc.

### CODE REVIEW

**Comment by ioquatix** [comment]
Thanks!

**Comment by matthewd** [comment]
Did this mean "interactively"? The existing use of "iteratively" seems more plausible to me.

**Comment by ioquatix** [comment]
Fair point, let me rewrite it :)

**Comment by TonyCTHsu** [comment]
Wow.... actually that is true. I guess I was blind..

**Pull request merged**
