### PR TITLE
Let's keep a changelog

### PR DESCRIPTION
**Pull request by twitnithegirl**
Hi friends,
This PR consolidates and reformats the contents of HISTORY.md and NEWS.md into a new CHANGELOG.md.

I did my best to reformat the existing history closer to the format of Keep a Changelog. I went with this specific format so that we have a reference as we begin in earnest to maintain better release history going forward. I haven't done anything yet to reconstruct release history from _the lost days_ and it may be that those releases will just go undocumented like that semester you stopped writing in your diary in middle school. 

As discussed [here](https://github.com/rack/rack/issues/1263) along with maintaining a changelog I also move that we can go ahead and soft retire rack.github.io by taking the link out of the rack/rack repo description. After combing through to see if there is any content there that isn't reflected in github we can just kill the repo.

[Aaron](@tenderlove) and [Leah](@chneukirchen)mentioned [a while back](https://github.com/rack/rack/issues/1245) that it would be good to have more documentation types around here and I'm happy to help in that capacity.

I'd love to hear any feedback or questions about this change.

### CODE REVIEW

**Comment by twitnithegirl** [comment]
Oops, sorry I didn't [ci skip]

**Comment by twitnithegirl** [comment]
Also think we should have a list of all currently deprecated features and when we expect them to be deprecated. I could put that just before the break between the new and historic changelog and we can track things that become deprecated and their anticipated retirement versions in the changelog as they come. Alternatively we can track deprecation in its own file and just link it from the README.

**Comment by tenderlove** [comment]
I have mixed feelings about changelogs.  I want to communicate overarching changes, but not necessarily every change.  IMO NEWS is better for that (Ruby recently removed changelogs in favor of just NEWS).  I guess, historically changelogs have been information for other developers of that library where NEWS is for the consumer of the library.  Since the Git history is available to everyone, changelogs seem irrelevant to me.  If we're willing to treat this changelog more like NEWS, targeted to *consumers* of rack, then I'm good with this.

**Comment by twitnithegirl** [comment]
@tenderlove thanks for the feedback. Keeping it more consumer focused makes sense. What are your thoughts re: the historical changes? Keep them here and just make sure future updates are only items relevant to end-users?

**Comment by tenderlove** [comment]
@twitnithegirl Ya, lets do that.  I think keeping it consumer focused going forward would be perfect.

**Comment by tenderlove** [comment]
I'll merge this and then we can refer back to this ticket for guidance on changelog updates.  How does that sound?

**Comment by twitnithegirl** [comment]
@tenderlove Sounds good to me. Thanks! 🎆

**Pull request merged**
