### PR TITLE
Move Rack::Request convienence methods to Helpers

### PR DESCRIPTION
**Pull request by maclover7**
Tried my best to migrate behavior to Helpers. Bit difficult since same
methods already exist there.

cc @tenderlove

### CODE REVIEW

**Comment by maclover7** [comment]
Just FYI, was having trouble setting up my development environment with CGI and stuff.

**Comment by tenderlove** [comment]
@maclover7 I'm so sorry I missed this.  I merged a PR from @sgrif for the same thing.  BTW, this PR shouldn't have introduced caching to the params method.

Do we need the values at method for backwards compat?  If so, can you modify this PR to just add values_at and I'll merge that?

**Comment by maclover7** [comment]
@tenderlove No problem ❤️ :) I will update my PR to only include the `values_at` method.

**Comment by maclover7** [comment]
Updated.

**Comment by tenderlove** [comment]
@maclover7 thank you so much! I really appreciate it!!

**Pull request merged**
