### PR TITLE
Fix: Add `to_hash` to wrap Hash and Session classes on `stringify_keys`

### PR DESCRIPTION
**Pull request by oleh-demyanyuk**
When using Rails application and go to Sidekiq Web management page I've got the following error:
```
undefined method 'transform_keys' for #<ActionDispatch::Request::Session:0x00007f8fa6d3bcc8>
```
With code :
```
        def stringify_keys(other)
          other.transform_keys(&:to_s) # <-- Error happened here
        end
      end
```
Application Trace:
```
/Users/olehd/.rvm/gems/ruby-2.3.7/bundler/gems/rack-e82f06b354fa/lib/rack/session/abstract/id.rb:185:in `stringify_keys'
/Users/olehd/.rvm/gems/ruby-2.3.7/bundler/gems/rack-e82f06b354fa/lib/rack/session/abstract/id.rb:121:in `update'
/Users/olehd/.rvm/gems/ruby-2.3.7/bundler/gems/rack-e82f06b354fa/lib/rack/session/abstract/id.rb:290:in `prepare_session'
/Users/olehd/.rvm/gems/ruby-2.3.7/bundler/gems/rack-e82f06b354fa/lib/rack/session/abstract/id.rb:249:in `context'
/Users/olehd/.rvm/gems/ruby-2.3.7/bundler/gems/rack-e82f06b354fa/lib/rack/session/abstract/id.rb:244:in `call'
/Users/olehd/.rvm/gems/ruby-2.3.7/bundler/gems/rack-e82f06b354fa/lib/rack/urlmap.rb:77:in `block in call'
/Users/olehd/.rvm/gems/ruby-2.3.7/bundler/gems/rack-e82f06b354fa/lib/rack/urlmap.rb:61:in `each'
/Users/olehd/.rvm/gems/ruby-2.3.7/bundler/gems/rack-e82f06b354fa/lib/rack/urlmap.rb:61:in `call'
/Users/olehd/.rvm/gems/ruby-2.3.7/bundler/gems/rack-e82f06b354fa/lib/rack/builder.rb:176:in `call'
sidekiq (5.2.7) lib/sidekiq/web.rb:103:in `call'
sidekiq (5.2.7) lib/sidekiq/web.rb:108:in `call'
actionpack (5.0.7.2) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.0.7.2) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:727:in `call'
```

Gems Versions:
ruby - `2.3.7`
rails - `5.0.7.2`
sidekiq - `5.2.7`
rack - `master` branch

This PR solved issue.

### CODE REVIEW

**Comment by ahmadhasankhan** [comment]
I am also facing this issue

```
NoMethodError (undefined method `to_h' for #<ActionDispatch::Request::Session:0x7fcd03626f10 not yet loaded>
Did you mean?  to_s):
  
rack (2.1.0) lib/rack/session/abstract/id.rb:212:in `stringify_keys'
rack (2.1.0) lib/rack/session/abstract/id.rb:148:in `update'
rack (2.1.0) lib/rack/session/abstract/id.rb:317:in `prepare_session'
rack (2.1.0) lib/rack/session/abstract/id.rb:276:in `context'
rack (2.1.0) lib/rack/session/abstract/id.rb:271:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.1.0) lib/rack/urlmap.rb:77:in `block in call'
rack (2.1.0) lib/rack/urlmap.rb:61:in `each'
rack (2.1.0) lib/rack/urlmap.rb:61:in `call'
rack (2.1.0) lib/rack/builder.rb:176:in `call'
rollbar (2.23.1) lib/rollbar/middleware/rack/builder.rb:16:in `block in call_with_rollbar'
rollbar (2.23.1) lib/rollbar.rb:145:in `scoped'
rollbar (2.23.1) lib/rollbar/middleware/rack/builder.rb:14:in `call_with_rollbar'
sidekiq (6.0.4) lib/sidekiq/web.rb:104:in `call'
sidekiq (6.0.4) lib/sidekiq/web.rb:109:in `call'
actionpack (5.0.7.2) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.0.7.2) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:727:in `call'

```

**Comment by ahmadhasankhan** [comment]
I am also facing this issue

```
NoMethodError (undefined method `transform_keys' for #<ActionDispatch::Request::Session:0x7fe692288f68 not yet loaded>):
  
rack (2.1.0) lib/rack/session/abstract/id.rb:212:in `stringify_keys'
rack (2.1.0) lib/rack/session/abstract/id.rb:148:in `update'
rack (2.1.0) lib/rack/session/abstract/id.rb:317:in `prepare_session'
rack (2.1.0) lib/rack/session/abstract/id.rb:276:in `context'
rack (2.1.0) lib/rack/session/abstract/id.rb:271:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.1.0) lib/rack/urlmap.rb:77:in `block in call'
rack (2.1.0) lib/rack/urlmap.rb:61:in `each'
rack (2.1.0) lib/rack/urlmap.rb:61:in `call'
rack (2.1.0) lib/rack/builder.rb:176:in `call'
rollbar (2.23.1) lib/rollbar/middleware/rack/builder.rb:16:in `block in call_with_rollbar'
rollbar (2.23.1) lib/rollbar.rb:145:in `scoped'
rollbar (2.23.1) lib/rollbar/middleware/rack/builder.rb:14:in `call_with_rollbar'
sidekiq (6.0.4) lib/sidekiq/web.rb:104:in `call'
sidekiq (6.0.4) lib/sidekiq/web.rb:109:in `call'
actionpack (5.0.7.2) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.0.7.2) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.7.2) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.7.2) lib/action_dispatch/routing/route_set.rb:727:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
scout_apm (2.6.6) lib/scout_apm/instant/middleware.rb:53:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
scout_apm (2.6.6) lib/scout_apm/middleware.rb:20:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.1.0) lib/rack/etag.rb:27:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.1.0) lib/rack/conditional_get.rb:27:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.1.0) lib/rack/head.rb:14:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.1.0) lib/rack/session/abstract/id.rb:277:in `context'
rack (2.1.0) lib/rack/session/abstract/id.rb:271:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/cookies.rb:613:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
activerecord (5.0.7.2) lib/active_record/migration.rb:553:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.2) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.2) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rollbar (2.23.1) lib/rollbar/middleware/rails/rollbar.rb:25:in `block in call'
rollbar (2.23.1) lib/rollbar.rb:145:in `scoped'
rollbar (2.23.1) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
rollbar (2.23.1) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
railties (5.0.7.2) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.2) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.2) lib/rails/rack/logger.rb:24:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack-timeout (0.6.0) lib/rack/timeout/core.rb:151:in `block in call'
rack-timeout (0.6.0) lib/rack/timeout/support/timeout.rb:19:in `timeout'
rack-timeout (0.6.0) lib/rack/timeout/core.rb:150:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/request_id.rb:24:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.1.0) lib/rack/method_override.rb:24:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.1.0) lib/rack/runtime.rb:24:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack-timeout (0.6.0) lib/rack/timeout/core.rb:151:in `block in call'
rack-timeout (0.6.0) lib/rack/timeout/support/timeout.rb:19:in `timeout'
rack-timeout (0.6.0) lib/rack/timeout/core.rb:150:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
activesupport (5.0.7.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/executor.rb:12:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
actionpack (5.0.7.2) lib/action_dispatch/middleware/static.rb:136:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
rack (2.1.0) lib/rack/sendfile.rb:113:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
railties (5.0.7.2) lib/rails/engine.rb:522:in `call'
newrelic_rpm (6.8.0.360) lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
puma (3.8.2) lib/puma/configuration.rb:224:in `call'
puma (3.8.2) lib/puma/server.rb:600:in `handle_request'
puma (3.8.2) lib/puma/server.rb:435:in `process_client'
puma (3.8.2) lib/puma/server.rb:299:in `block in run'
puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

```

**Comment by ioquatix** [comment]
What is the value of `other` in the failing case?

Do we prefer `to_h` or `to_hash`?

cc @tenderlove @rafaelfranca

**Comment by ahorek** [comment]
in my opinion, https://github.com/rack/rack/pull/1401 and https://github.com/rack/rack/pull/1391 should be reverted

adding #to_hash will fix the issue, but the original performance improvement for hash arguments is gone
`Rack::Session::Abstract::SessionHash` is actually 40% slower
and `ActionDispatch::Request::Session` is broken

**Comment by ioquatix** [comment]
@ahorek I don't disagree with you.

I can merge this, and then can you make a follow up PR to improve both performance and spec coverage on the downstream requirements? We can get it out in 2.2.0

**Comment by ahorek** [comment]
yes, I think it's ok to merge.

after this PR, the change in https://github.com/rack/rack/pull/1401 should be reverted anyway, because 
`Rack::Session::Abstract::SessionHash` does respond #to_hash and the custom #transform_keys method is no longer necessary

**Comment by ioquatix** [comment]
Can you make a PR to revert #1401 .

**Comment by kapso** [comment]
This still seems to be an issue for me with Rack `v2.1.1`

**Comment by PikachuEXE** [comment]
@kapso The revert of #1401 is not included in `2.1.1`
image

**Comment by Rim-777** [comment]
Hello, I have the same issue with Rack v2.1.1, could anyone please give me a hint what need I do to solve it?

**Comment by mati0090** [comment]
In your `Gemfile` use following line as temporary solution:
`gem 'rack', git: 'git@github.com:rack/rack.git', :ref => 'f690bb71425aa31d7b9b3113829af773950d8ab5'
`

**Comment by garside** [comment]
If you need to deploy this to heroku, use this format in the gemfile instead or your build will fail with private key errors.

```
gem 'rack', github: 'rack/rack', :ref => 'f690bb71425aa31d7b9b3113829af773950d8ab5'
```

**Comment by Rim-777** [comment]
@mati0090 Thank you, it helped.
@garside Thank you too

**Comment by jjstafford** [comment]
@garside that worked great.  Hopefully this is merged soon....

**Comment by saiqulhaq** [comment]
can we have v2.1.1.1 version to release this?

**Comment by chongfai13** [comment]
> In your `Gemfile` use following line as temporary solution:
> `gem 'rack', github: 'rack/rack', ref: 'f690bb71425aa31d7b9b3113829af773950d8ab5'`

I encountered this error after adding 

Could not find gem 'browserify-:q!ils' in any of the gem sources listed in your Gemfile or in gems cached in vendor/cache.

**Comment by saiqulhaq** [comment]
> > In your `Gemfile` use following line as temporary solution:
> > `gem 'rack', github: 'rack/rack', ref: 'f690bb71425aa31d7b9b3113829af773950d8ab5'`
> 
> I encountered this error after adding
> 
> Could not find gem 'browserify-:q!ils' in any of the gem sources listed in your Gemfile or in gems cached in vendor/cache.

your issue is not related to rack
this is my Gemfile
image
I updated it 2 hours ago without any problem after bundle install

**Comment by chongfai13** [comment]
> > > In your `Gemfile` use following line as temporary solution:
> > > `gem 'rack', github: 'rack/rack', ref: 'f690bb71425aa31d7b9b3113829af773950d8ab5'`
> > 
> > 
> > I encountered this error after adding
> > Could not find gem 'browserify-:q!ils' in any of the gem sources listed in your Gemfile or in gems cached in vendor/cache.
> 
> your issue is not related to rack
> this is my Gemfile
> image
> I updated it 2 hours ago without any problem after bundle install

It works! Terima Kasih banyak banyak

**Comment by ioquatix** [comment]
@tenderlove should we backport this and cut a v2.1.2 release or wait until a v2.2.0 release?

**Comment by natematykiewicz** [comment]
I’d love a release. My Sidekiq admin page is busted and it took my a while to figure out what the problem was.

**Comment by balexandr** [comment]
> I’d love a release. My Sidekiq admin page is busted and it took my a while to figure out what the problem was.

After we put the fix in place, we noticed that our Sidekiq page is just blank now. Anyone else having this issue?

**Comment by estebanbouza** [comment]
This approach works on development:

```
gem 'rack', github: 'rack/rack', ref: 'f690bb71425aa31d7b9b3113829af773950d8ab5'
```

But in Production, I get:

```
Step #1 - "docker-build": Step 10/11 : RUN cd /app && RAILS_ENV=production SECRET_KEY_BASE=xxx rails assets:precompile
Step #1 - "docker-build": ---> Running in 57e0841136
Step #1 - "docker-build": /usr/local/lib/ruby/2.6.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'rack' (~> 2.0, >= 2.0.8) among 228 total gem(s) (Gem::MissingSpecError)
Step #1 - "docker-build": Checked in 'GEM_PATH=/xxx/.gem/ruby/2.6.0:/usr/local/lib/ruby/gems/2.6.0:/usr/local/bundle', execute `gem env` for more information
Step #1 - "docker-build": from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
```

Which seems to be the expected behavior based on [bundler doc](https://bundler.io/v1.12/git.html)

> Because RubyGems lacks the ability to handle gems from git, any gems installed from a git repository will not show up in gem list.

Any clue? A new release would be appreciated otherwise.

**Comment by Shleeble** [comment]
ETA til 2.1.2?

**Comment by springerigor** [comment]
If you are waiting for the 2.1.2 you can temporarily monkey patch `rack`:

Fo Rails projects you can create e.g. `config/initializers/rack_monkey_path.rb` file:

```ruby
# Monkey patch `stringify_keys` to make rack 2.1.1 compatible with Sidekiq UI Admin panel.
# Should be removed when 2.1.2 is released.
# https://github.com/rack/rack/pull/1428
module Rack
  module Session
    module Abstract
      class SessionHash
        private

        def stringify_keys(other)
          other.to_hash.transform_keys(&:to_s)
        end
      end
    end
  end
end

```

**Comment by Rim-777** [comment]
> If you need to deploy this to heroku, use this format in the gemfile instead or your build will fail with private key errors.
> 
> ```
> gem 'rack', github: 'rack/rack', :ref => 'f690bb71425aa31d7b9b3113829af773950d8ab5'
> ```

I got some problems with deploy on AWS. is there an appropriate ref hash for that?

**Comment by jbilbo** [comment]
v2.1.2 has been released. Now you can
```
bundle update rack
```
and make sure you use v2.1.2 or higher to avoid this issue.

**Comment by ArturT** [comment]
If you updated your app to rack 2.1.2 and you see a blank page for Sidekiq Web UI then there is an issue in Sidekiq repo for it https://github.com/mperham/sidekiq/issues/4440

**Pull request merged**
