### PR TITLE
Strip quotes from around multipart encodings

### LINKED ISSUE #905: Error uploading binary files in Rails 4.2, Ruby 2.1.2
After migrating to rails 4.2 there was an error when upload png files from Unity3d app like this:

```c#
WWWForm form = new WWWForm();
form.AddField( "user_sid", sid, System.Text.Encoding.UTF8 );
form.AddBinaryData( "file", data, fileName, "image/png; charset=UTF-8" );
AddRequest( "path/to/upload", form, null, false );
```

In the server side:

```
ArgumentError (unknown encoding name - "utf-8"):
  rack (1.6.4) lib/rack/multipart/parser.rb:211:in `find'
  rack (1.6.4) lib/rack/multipart/parser.rb:211:in `block in tag_multipart_encoding'
  rack (1.6.4) lib/rack/multipart/parser.rb:207:in `each'
  rack (1.6.4) lib/rack/multipart/parser.rb:207:in `tag_multipart_encoding'
  rack (1.6.4) lib/rack/multipart/parser.rb:75:in `block (2 levels) in parse'
  rack (1.6.4) lib/rack/multipart/parser.rb:250:in `get_data'
  rack (1.6.4) lib/rack/multipart/parser.rb:74:in `block in parse'
  rack (1.6.4) lib/rack/multipart/parser.rb:56:in `loop'
  rack (1.6.4) lib/rack/multipart/parser.rb:56:in `parse'
  rack (1.6.4) lib/rack/multipart.rb:25:in `parse_multipart'
  rack (1.6.4) lib/rack/request.rb:375:in `parse_multipart'
  rack (1.6.4) lib/rack/request.rb:207:in `POST'
  actionpack (4.2.1) lib/action_dispatch/http/request.rb:308:in `POST'
  actionpack (4.2.1) lib/action_dispatch/http/parameters.rb:14:in `parameters'
  actionpack (4.2.1) lib/action_dispatch/http/filter_parameters.rb:37:in `filtered_parameters'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:22:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  simple_captcha2 (0.3.4) lib/simple_captcha/middleware.rb:26:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  railties (4.2.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.1) lib/rails/application.rb:164:in `call'
  newrelic_rpm (3.12.0.288) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  passenger (5.0.6) lib/phusion_passenger/rack/thread_handler_extension.rb:85:in `process_request'
  passenger (5.0.6) lib/phusion_passenger/request_handler/thread_handler.rb:155:in `accept_and_process_next_request'
  passenger (5.0.6) lib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
  passenger (5.0.6) lib/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
  passenger (5.0.6) lib/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
```

problem in quotes...

### PR DESCRIPTION
**Pull request by raggi**
Fixes #905

### CODE REVIEW

**Comment by spastorino** [comment]
@raggi seems good, you prefer us to merge it or wanna do it yourself?

**Comment by raggi** [comment]
It was mostly to let you know that it was here, feel free to merge. There's also been enough changes in places that I'm going to ask for more eyes if/when I patch now :heart:

**Comment by milkcocoa** [comment]
@raggi Is there any plan to back port this patch to 1.6.x?

**Comment by raggi** [comment]
@milkcocoa i don't do releases anymore, you'll have to beg @tenderlove

**Comment by garside** [comment]
@milkcocoa Dunno if you still need this for `1.6.x`. I just ran into the issue today. I threw together a quick monkey patch cause I couldn't find an easier/better way to get it fixed. 

**config/initializers/rack_multipart_monkeypatch.rb**:
```ruby
module Rack
  module Multipart
    class Parser
      old_tag_multipart = instance_method(:tag_multipart_encoding)

      # Unity puts quotes around the chartype and doesn't allow it to change
      # Rack patched this but will not be backporting the fix
      define_method(:tag_multipart_encoding) do |filename, content_type, name, body|
        content_type.gsub!('"utf-8"', 'utf-8')
        old_tag_multipart.bind(self).(filename, content_type, name, body)
      end
    end
  end
end

```

**Pull request merged**
