### PR TITLE
Support for the Partitioned cookie attribute

### PR DESCRIPTION
**Pull request by dchitragupt-conga**
MR

### CODE REVIEW

**Comment by jeremyevans** [comment]
I'm not in favor of backporting this feature, but if we do, we certainly shouldn't backport to 2.0-stable, which is unmaintained. 2.2-stable is in security maintenance only mode, so it wouldn't make sense to backport to that either.  Considering we've made breaking changes to 3.0-stable, I suppose you could argue for backporting to that, but that's as far as I would go, assuming we plan on backporting the feature at all.

**Comment by dchitragupt-conga** [comment]
We are using older versions of rack and can’t update to latest version. Due to this we are failing features.


Get Outlook for iOS<https://aka.ms/o0ukef>

Increase revenue lifecycle certainty
Leave a review
|Support|Twitter|
LinkedIn
________________________________

**Comment by mikegee** [comment]
> We are using older versions of rack and can’t update to latest version.

That is certainly unfortunate. Please understand that your particular application cannot dictate how past versions of Rack are maintained. See https://github.com/rack/rack/blob/main/SECURITY.md for Rack's maintenance policy.

**Comment by jeremyevans** [comment]
I'm closing this.  There is no way we are going to apply patches to 2.0-stable at this point.

**Pull request closed without merging**
