### PR TITLE
Add support for custom hmac.

### PR DESCRIPTION
**Pull request by frodsan**

### CODE REVIEW

**Comment by tenderlove** [comment]
This change doesn't seem to be equivalent.  Can you pass a string instead of an object?  Also, could you add a test?

**Comment by frodsan** [comment]
I think it iss supported: https://github.com/ruby/ruby/blob/master/ext/openssl/ossl_digest.c#L40..L52.

But I will revert it. I will pass the class instead. I will add a test. Ty.

**Comment by tenderlove** [comment]
> But I will revert it to avoid confusion. I will pass the class instead. I will add a test. Ty.

Sounds good. Let me know when you've updated and I'll merge this.

**Comment by frodsan** [comment]
Closing this in favor of https://github.com/rack/rack/pull/958

**Pull request closed without merging**
