### PR TITLE
Fix Utils.build_nested_query to URL-encode all query string fields

### PR DESCRIPTION
**Pull request by jdufresne**
In the formatted query string, the field should be fully URL-encoded. The previous implementation left the square brackets as un-escaped.

It was noticed that if params were provided as a nested hash it produced a different result than a hash of string fields. For example, the params

    { 'q[s]' => 'name' }

would result in the query string:

    q%5Bs%5D=name

but

    { q: { s: 'name' } }

would result in:

    q[s]=name

Both forms now produce the same correct result with fully URL-encoded params.

### CODE REVIEW

**Comment by ioquatix** [comment]
I'm okay with this but it seems like a potential breaking change.

**Review by jeremyevans — APPROVED** [review]
I agree that this could potentially be breaking, but RFC 3986 is clear that `[` and `]` are reserved characters and should be percent encoded.  So I think we should merge this.

**Comment by AlexWayfer** [comment]
Yeah, sadly it has broken tests of my Rack-based framework unclear and non-expected, just by some patch-version release.

**Comment by ioquatix** [comment]
IIUC, one way to avoid this problem in your test is to avoid asserting the encoded representation and actually parse the URL and extract the query parameters. This should work regardless of the encoding and is probably a more robust test in general.

**Comment by AlexWayfer** [comment]
> IIUC, one way to avoid this problem in your test is to avoid asserting the encoded representation and actually parse the URL and extract the query parameters. This should work regardless of the encoding and is probably a more robust test in general.

I can agree. I've checked the tests again. It's simple tests for `path` method, returning String, sometimes with query. So, parsing it with standard tools may be a pain.

Maybe I should add `URI.decode_uri_component`, but, again, not sure how safe it is.

**Comment by ioquatix** [comment]
> Maybe I should add URI.decode_uri_component

I think this is probably the correct approach.

**Pull request merged**
