### PR TITLE
Change SPEC to not allow uppercase header keys

### PR DESCRIPTION
**Pull request by jeremyevans**
Also, update CHANGELOG with other spec changes made since 2.2.

Implements #1592

External tests are broken because this is a huge breaking change.  If we are sure that we want this, we should disable the external CI jobs until the related projects have been fixed.

### CODE REVIEW

**Review by ioquatix — APPROVED** [review]
There will be a lot of small details but I approve the general direction and think this is a great first step.

**Comment by ioquatix** [comment]
Fixing external tests seems straight forward so I don't think this should be a blocker. However, I'd suggest we merge this and then clean up the remaining external issues. Once we confirm the direction, it won't be hard to sort out the downstream dependencies.

**Comment by ioquatix** [comment]
Okay @jeremyevans all external tests are passing. Falcon was already 100% compatible :)

**Comment by ioquatix** [comment]
@tenderlove do you have any reservations regarding this?

**Comment by tenderlove** [comment]
> @tenderlove do you have any reservations regarding this?

No, I think this is great.  Thanks for doing this work @jeremyevans!!

**Pull request merged**
