### PR TITLE
CI: Drop Travis configuration file and README build status badge

### PR DESCRIPTION
**Pull request by olleolleolle**
**Update**: After communicating with Aaron, this PR removes the Travis configuration and the build badge.

<details>

(This PR supersdes #1220.)

This PR updates the Travis CI settings.

- Add  `jruby-9.1.17.0` (which passes its tests)
- Add `rbx-3.107`. This makes that platform build - with 1 failing test

## Observations

- Other more modern JRuby is tested in CircleCI.
- Travis CI matrix member `jruby-9.0.4.0` stalls its tests. "No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself."

## Rubinius

The remaining test failure on Rubinius is now

```
  1) Failure:
Rack::MethodOverride#test_0002_sets rack.errors for invalid UTF8 _method values [/home/travis/build/rack/rack/test/spec_method_override.rb:32]:
--- expected
+++ actual
@@ -1,2 +1,2 @@
-"Invalid string for method
-"
+# encoding: ASCII-8BIT
+""
```

Searching for the `encoding` string turned up this:https://github.com/rack/rack/blob/d74c73a782516359f51513e2d510141db1a092a4/lib/rack/lint.rb#L337-L340

<summary>What this was, before talking about it</summary>

</details>

### CODE REVIEW

**Comment by tenderlove** [comment]
Any reason we should keep the Travis build?  I'm not particularly interested in keeping two CI systems going.  I guess the only difference is that we test rbx on Travis, and we should probably mark it as "allowing failures" (which, if we're going to let it fail why bother testing?) 🤷‍♀️

**Comment by tenderlove** [comment]
> A resolution which is a file removal can also get us to greener builds.

Sounds good to me.  Want to rm the travis file and I'll merge this?

**Comment by olleolleolle** [comment]
@tenderlove The file is removed, the README updated. (I didn't add a CHANGELOG line about this change.)

**Comment by tenderlove** [comment]
Thank you!!

**Pull request merged**
