### PR TITLE
Bump minor version.

### PR DESCRIPTION
**Pull request by ioquatix**
See <https://github.com/rack/rack/milestone/26?closed=1> and the change log for more details.

### CODE REVIEW

**Comment by Earlopain** [comment]
Did someone have a chance to check out https://github.com/rails/rails/issues/52066#issuecomment-2156427472? I don't think an issue was made.

**Comment by ioquatix** [comment]
Nope, this is the first time we saw it.

IIUC, application code should not be specifying `transfer-encoding: chunked`. If your intention is to force streaming, either use a streaming response OR don't implement `to_ary` on the response body.

**Comment by Earlopain** [comment]
I'll just link your reply there, I'm not qualified to make any sort of assessment on this. Thanks (:

**Comment by ioquatix** [comment]
Appreciate it!

**Comment by ioquatix** [comment]
@Earlopain appreciate your attention to detail and cross-references!

**Pull request merged**
