### PR TITLE
Add falcon as an option by default.

### PR DESCRIPTION
**Pull request by ioquatix**
* Server code is available here: https://github.com/socketry/falcon

### CODE REVIEW

**Comment by rafaelfranca** [comment]
Thank you for the pull request but I think it is too soon to add it to the default list.

**Comment by ioquatix** [comment]
Why not make it possible for web servers to register themselves somehow?

**Comment by rafaelfranca** [comment]
That sounds good to me

**Comment by parndt** [comment]
@rafaelfranca is it still too soon? I'm using Falcon for things in production already and it's a great option. Thanks 😄

**Comment by ioquatix** [comment]
I would like to implement a PR to allow servers to dynamically add themselves. We could merge this in the meantime, but I think it makes sense for it to be dynamic based on what gems the user has loaded.

**Comment by simi** [comment]
:thinking: What changed your opinion @rafaelfranca?

**Comment by rafaelfranca** [comment]
More than one year with falcon being out there and people using it.

**Comment by ioquatix** [comment]
Thanks for merging.

Just FYI, I've added falcon tests using rack 1.x and master branch: https://travis-ci.com/socketry/falcon/builds/98681821 (check the Gemfile used).

e.g. https://travis-ci.com/socketry/falcon/jobs/173157848

It will be interesting to track changes to ensure compatibility.

Is there any discussion around what Rack 3 might look like?

I know there was at least some discussion about removing the need for rewindability.

**Pull request merged**
