### PR TITLE
Remove dependency on rack-session, and development dependency on minitest-sprint

### PR DESCRIPTION
**Pull request by jeremyevans**

### CODE REVIEW

**Comment by jeremyevans** [comment]
Looks like we need to update at least rack-attack to require rack-session as a dependency for the external specs to pass (maybe only development dependency if it is only used in the specs).

**Comment by ioquatix** [comment]
Can you make a PR to rack-attack too? We can then merge them in order so they both pass.

**Review by ioquatix — APPROVED** [review]

**Comment by ioquatix** [comment]
https://github.com/rack/rack-attack/pull/581

**Comment by jeremyevans** [comment]
Looks like that rack-attack PR doesn't work. I'm not sure how rack-session interacts with rack 2.2 and below.

I pushed another commit to this PR that modifies the external rack-attack tests to also require rack-session. I think this is a better approach.

**Comment by jeremyevans** [comment]
Looks like the last commit worked, so I'll merge this.

**Comment by ioquatix** [comment]
Ultimately I think external dependencies will need to sniff rack 2.x or 3.x and pull in rack-session as needed.

**Pull request merged**
