### PR TITLE
Rack::File -> Rack::Files

### PR DESCRIPTION
**Pull request by postmodern**
Renamed `Rack::File` to `Rack::Files`, since it can serve arbitrary _files_ from a root directory. Once we can remove `Rack::File`, we can no longer worry about name conflicts between `::File` and `Rack::File`.

### CODE REVIEW

**Comment by ioquatix** [comment]
@tenderlove I can rebase and merge this. I can add a deprecation notice and aim for removing in 3.0?

**Comment by tenderlove** [comment]
@ioquatix sounds great!  Go for it

**Comment by ioquatix** [comment]
Okay rebasing today.

**Comment by ioquatix** [comment]
Merged.

**Pull request closed without merging**
