### PR TITLE
Dynamic cookie key for session ID

### LINKED ISSUE #1155: Dynamic cookie key for session stores
The abstract session store implementation ([lib/rack/session/abstract/id.rb](https://github.com/rack/rack/blob/master/lib/rack/session/abstract/id.rb)) uses an instance variable, initialized at startup, to determine the name of the cookie it will use to fetch/set a session's id.

I recently ran into a scenario where it would be convenient to have the option to make this cookie name dynamic. For example, a user could visit my website at `www.example.com` and have one session, then they could visit `www.example.com/admin` and have a completely different one. I could also see instances where the session could change dynamically based on cookies, headers, IP address, or any other information the webserver has.

Since these cases are very rare, and may not be best practice, I wanted to get some feedback on this feature request. If there's any desire for such functionality, I'll happily submit a PR.

I'll post one example of how this feature request could be addressed. Please let me know if this is something desirable in the rack mainline.

### PR DESCRIPTION
**Pull request by j1mmie**
Allows custom session stores that extend the abstract session store to
dynamically select which cookie key will be used for fetching/setting
the session's id. This allows the user to maintain multiple, different sessions.
The web application can determine which session to be used for the
current request based on any number of conditions (URL, headers, cookies, IP,
etc).

Fixes #1155

No tests are written for this change yet. Please let me know if this
functionality is desired in rack, or similar functionality with a different
implementation, and I'll happily add tests and seek review. Thanks!

### CODE REVIEW

**Comment by rafaelfranca** [comment]
I like the idea. @tenderlove @eileencodes thoughts?

**Comment by tenderlove** [comment]
I'm fine with this. Needs tests and docs though. The method might get
deleted without them!

**Comment by rafaelfranca** [comment]
@jeremy what you are describing is basically what is possible today https://github.com/rack/rack/issues/1155#issuecomment-301169716.

I also think it is better, but the current API is not good in my opinion. It know too much about the rack implementation.

**Comment by jeremy** [comment]
Using "well-known" Rack env keys is the normal, public way of interacting with Rack components. It's not like peeking underneath a public interface at private implementation details—it _is_ the public interface. So, given the Rack API style, providing runtime config in this way seems as natural as we can hope.

**Comment by j1mmie** [comment]
Oops didn't mean to close this. Reopened.

@jeremy @rafaelfranca Can either of you confirm that @hiteshsharma's suggestion works in the latest version of Rack? I haven't had a chance to test, but in my version this did not work.

I agree with @jeremy's suggestion, the cookie name should be decided *very* early on, possibly at the Rack level.

**Comment by jeremyevans** [comment]
As `env['rack.session.options']` already exists and is supported, I plan to close this unless another core team member objects.

**Pull request closed without merging**
