### PR TITLE
Documenting Rack::Utils::HeaderHash keys restrictions [ci skip]

### PR DESCRIPTION
**Pull request by esparta**
Currently the class does not accept nil as keys on their operations

### CODE REVIEW

**Comment by tenderlove** [comment]
PR looks good, but I'm not sure if we explicitly don't support `nil`, or we just don't know what to do to support it.  I think if we were to explicitly not support `nil`, it should raise an `ArgumentError` rather than just getting an exception from `downcase` called on `nil`.

**Comment by rafaelfranca** [comment]
By the purpose of the hash I'd say we should not support it. Unless you think `nil` has a header name make sense.

**Comment by tenderlove** [comment]
> By the purpose of the hash I'd say we should not support it. Unless you think nil has a header name make sense.

I really don't think `nil` as a header name makes sense. @esparta can you change these to raise an `ArgumentError`?

**Comment by esparta** [comment]
I guess I can do it, but I don't know if we should.

Adding a begin block +re-raise or an additional if for a case it shouldn't happen frequently (or is something wrong with the call chain), would be costly. I don't know if originally was intended to let it fail.

The methods on `HeaderHash` (`#initialize`, `#merge`, etc) are called by `#initialize` or `#call` within these classes: `Chunked`, `CommonLogger`, `ConditionalLogger`, `ContentType`, `ContentLength`, `Deflater`, `Link`, `ShowStatus`. The one concern most is `Response#initialize`.

I got this because some internal/in-house middleware was misbehaving and leads me to that error, that took me a some time to figure out what was going on, so that's why I mean to at least document it on comments and tests.

So, should I proceed?

**Comment by jeremyevans** [comment]
I don't think we should add tests for this.  It doesn't make sense to call out `nil` as not being supported, anything not a string will probably result in the same error (e.g. `Rack::Utils::HeaderHash.new(1=>2)`).  The documentation for HeaderHash states: `A case-insensitive Hash that preserves the original case of a header when set.`  I think this implies that keys should be strings.  At most we should just add a note to explicitly state that.

**Pull request closed without merging**
