### PR TITLE
Only use ::Rack::RegexpExtensions on Ruby 2.3

### PR DESCRIPTION
**Pull request by jeremyevans**
Ruby 2.4+ support Regexp#match? and does not require loading a
refinement.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
The refinement itself don't do anything in 2.4. Is there any overhead on calling `using` in a module that does nothing?

**Comment by jeremyevans** [comment]
Yes, there is overhead in CRuby, and I think also in JRuby, though someone with more JRuby experience could probably confirm.

**Comment by rafaelfranca** [comment]
👍

**Comment by ioquatix** [comment]
We will probably drop Ruby 2.3 in rack 2.3/3.0 depending on how the timeline works out. It's far out there in terms of EOL, and even 2.4 is almost EOL.

**Pull request merged**
