### PR TITLE
Fix inefficient assert pattern in Rack::Lint

### PR DESCRIPTION
**Pull request by eregon**
Fixes https://github.com/rack/rack/issues/1723

### CODE REVIEW

**Comment by eregon** [comment]
@jeremyevans Could you review and merge?

**Review by jeremyevans — APPROVED** [review]
I'm OK with these changes.  I'll give some other committers time for feedback, but if no feedback is received, I'll merge this next week.  Please ping me if I forget.

**Comment by ioquatix** [comment]
It looks fine to me.

Did you consider reversing the assert aguments?

**Comment by eregon** [comment]
@ioquatix I followed Jeremy's advice from https://github.com/rack/rack/issues/1723#issuecomment-738877460

**Comment by skipkayhil** [comment]
Would y'all accept a (partial) backport of this change to Rack `2-2-stable`? While working on skipkayhil/rails#5 we've run into a situation that makes a test worse because of the eager `inspect`.

Basically, in Rails there is a class put in the `env` that may raise when `to_s` is called on it: https://github.com/rails/rails/blob/0e5a99db5ac445e2bdfd19c911f62e65bbe0e45d/actionpack/lib/action_dispatch/middleware/remote_ip.rb#L168

When adding Rack::Lint to some of its tests, the error is now raised during the request when using Rack 2 instead of when the `to_s` is explicitly called later on.

**Comment by ioquatix** [comment]
I’d be okay with that.

**Pull request merged**
