### PR TITLE
Replace \t to 2 whitespaces in HISTORY.md

### PR DESCRIPTION
**Pull request by wildjcrt**
Styling PR.
I replace all \t to 2 whitespaces in HISTORY.md.

### CODE REVIEW

**Comment by tenderlove** [comment]
This is the way that vim generates the changelog entries.  Is there a compelling reason to change this since it means I'll have to figure out how to get vim to generate changelog entries with spaces?

**Comment by arthurnn** [comment]
@tenderlove if you wanna change to emacs :trollface: https://github.com/arthurnn/dotfiles/blob/master/.emacs.d/init.d/setup-etc.el#L23-L26

**Comment by tenderlove** [comment]
I don't understand, this ChangeLog style [came from Emacs](http://www.gnu.org/software/emacs/manual/html_node/emacs/Format-of-ChangeLog.html)

**Comment by arthurnn** [comment]
> this ChangeLog style came from Emacs
Thats right. 

Jokes aside. I dont think this PR adds value to the changelog, it is just the style we were following. So :-1:  i would say.

**Comment by mig-hub** [comment]
You guys managed to mix the editor war and the "tab vs spaces" war in a single thread.
It probably is somebody's wet dream.

**Pull request closed without merging**
