### PR TITLE
fix(session): add a proper #fetch method to Sessionhash

### PR DESCRIPTION
**Pull request by raszi**
Fixes rails/rails#25489

### CODE REVIEW

**Comment by raszi** [comment]
This PR is also relates to rack/rack#461

**Comment by raszi** [comment]
The failing tests seem to be unrelated to this PR.

**Comment by tenderlove** [comment]
Can you remove the changes in this patch that aren't related to the feature? Specifically the string quoting changes.

**Comment by raszi** [comment]
Well, I was following the Boy Scout Rule, but it is your call.

**Comment by raszi** [comment]
@tenderlove what do you think, is it okay now or should I rebase it?

**Comment by tenderlove** [comment]
I like the idea of a proper fetch method, but I'd like it better if the behavior was more similar to the fetch method on Hash. Can you make it behave the same way as Hash#fetch ?

--
Aaron Patterson
http://tenderlovemaking.com/
I'm on an iPhone so I apologize for top posting.

**Comment by raszi** [comment]
@tenderlove I am waiting for your answer on this.

**Comment by lerencao** [comment]
I think what @tenderlove  means is that `raise` when no key found and no default supplied, and yes also a block argument form.

**Comment by raszi** [comment]
The upstream took a different approach.

**Pull request closed without merging**
