### PR TITLE
Use Regexp match? instead of =~

### PR DESCRIPTION
**Pull request by krzysiek1507**
`Regexp#match?` is way faster than `=~` so we can gain a little bit of speed.

Ruby introduced `Regexp#match?` in 2.4 so we need to polyfill it for Ruby < 2.4.

### CODE REVIEW

**Comment by HoneyryderChuck** [comment]
Why not as a refinement?

**Comment by krzysiek1507** [comment]
I've copied this from [ActiveSupport](https://github.com/rails/rails/blob/ac717d65a31d05458588b78ea7719b79f8ea69e5/activesupport/lib/active_support/core_ext/regexp.rb#L8-L10).

**Comment by HoneyryderChuck** [comment]
if active support's implementation change (highly unlikely), you'll have to copy it again. If `match?` has been already defined, but it does something else, your code will break. 

Since rack officially supports ruby 2.2 or higher, and this would be an easy refinement, you could do it as easy as:

```ruby
module RegexpExtensions
  refine Regexp do
    def match?....

....

class Rack::Builder
  use RegexpExtensions if RUBY_VERSION > "2.3"
  ...

**Comment by krzysiek1507** [comment]
@HoneyryderChuck you are right. Changed! Thanks!

**Comment by krzysiek1507** [comment]
I think it's ready for review.

**Comment by mikegee** [comment]
seems legit to me 👍

**Pull request merged**
