### PR TITLE
Response documentation

### PR DESCRIPTION
**Pull request by ioquatix**
Follow up to feedback from https://github.com/rack/rack/pull/1517

### CODE REVIEW

**Comment by ioquatix** [comment]
@AlexWayfer all issues should be resolved here.

**Comment by AlexWayfer** [comment]
> @AlexWayfer all issues should be resolved here.

Wow, thank you for the work! :clap: 

I'm still not sure about `Response`'s instance in a `finish` result, but existing changes looks good.

**Comment by ioquatix** [comment]
@AlexWayfer I'm happy to add more clarification as to the result, but maybe at this point do you want to think about what would best satisfy you and propose it here in a comment so I can understand more what we can do to improve it?

**Comment by AlexWayfer** [comment]
> @AlexWayfer I'm happy to add more clarification as to the result, but maybe at this point do you want to think about what would best satisfy you and propose it here in a comment so I can understand more what we can do to improve it?

Thank you for this approach. I've created #1519 to do what I mean, want to see.

**Comment by jeremyevans** [comment]
These changes look fine to merge to me.

**Pull request merged**
